name: Add AWS Documentation Submodules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Ejecuta todos los domingos a medianoche

jobs:
  add-submodules:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'  # Asegúrate de que los submódulos se clonen también

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Add Submodules
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python add_submodules.py
