name: Generate Combined Documentation

on:
  workflow_dispatch:  # Esto permite que el flujo de trabajo sea ejecutado manualmente
  schedule:
    - cron: '0 0 * * 0'  # Ejecuta todos los domingos a medianoche

jobs:
  generate-documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'  # Asegúrate de que los submódulos se clonen también

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Generate Combined Documentation
      run: |
        # Crear un archivo de documentación combinado vacío
        echo "# AWS Documentation Combined" > combined_documentation.txt
        
        # Recorrer los submódulos y extraer todo el contenido de los archivos
        for submodule in $(git submodule foreach 'echo $name'); do
          echo "## Submódulo: $submodule" >> combined_documentation.txt
          
          # Recorrer todos los archivos dentro del submódulo y agregarlos al archivo combinado
          find "$submodule" -type f -exec cat {} \; >> combined_documentation.txt

          echo "\n\n" >> combined_documentation.txt  # Añadir salto de línea entre submódulos
        done
        
        # Verificar que el archivo combinado se haya creado correctamente
        cat combined_documentation.txt

    - name: Upload Combined Documentation as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: combined-documentation
        path: combined_documentation.txt
